export const gameStyles = {
  container: {
    backgroundColor: '#1E1E1E',
    border: '4px solid #FFFFFF',
    borderRadius: '8px',
    padding: '30px',
    fontFamily: "'Press Start 2P', monospace",
    color: '#14A800',
    boxShadow: '0 0 20px rgba(20, 168, 0, 0.3)',
    minWidth: '500px',
    minHeight: '500px',
  },
  gameBoard: {
    backgroundColor: '#0A0A0A',
    border: '2px solid #FFFFFF',
    position: 'relative' as const,
    margin: '0 auto',
    boxShadow: 'inset 0 0 20px rgba(20, 168, 0, 0.2)',
  },
  snakeSegment: {
    backgroundColor: '#14A800',
    border: '1px solid #0F7A00',
    position: 'absolute' as const,
    boxShadow: 'inset 1px 1px 0 rgba(255, 255, 255, 0.1)',
  },
  food: {
    backgroundColor: '#FFD700',
    border: '1px solid #FFA500',
    position: 'absolute' as const,
    borderRadius: '2px',
    boxShadow: '0 0 4px rgba(255, 215, 0, 0.5)',
  },
  dangerBlock: {
    backgroundColor: '#FF4444',
    border: '1px solid #CC0000',
    position: 'absolute' as const,
    boxShadow: '0 0 6px rgba(255, 68, 68, 0.7), inset 1px 1px 0 rgba(255, 255, 255, 0.2)',
  },
  ui: {
    textAlign: 'center' as const,
    marginBottom: '20px',
    fontSize: '16px',
    letterSpacing: '1px',
    color: '#FFFFFF',
  },
  gameOver: {
    position: 'absolute' as const,
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    backgroundColor: 'rgba(30, 30, 30, 0.95)',
    border: '3px solid #14A800',
    padding: '30px',
    textAlign: 'center' as const,
    borderRadius: '8px',
    boxShadow: '0 0 30px rgba(20, 168, 0, 0.5)',
  },
  button: {
    backgroundColor: '#14A800',
    color: '#000',
    border: 'none',
    padding: '10px 20px',
    fontSize: '10px',
    fontFamily: "'Press Start 2P', monospace",
    cursor: 'pointer',
    marginTop: '15px',
    borderRadius: '4px',
    transition: 'all 0.2s ease',
  },
  instructions: {
    fontSize: '12px',
    color: '#FFFFFF',
    marginTop: '10px',
    lineHeight: '1.5',
  }
};